image: docker:20
services:
  - docker:20-dind

variables:
  GITLAB_TAG: $CI_REGISTRY_IMAGE
  GITLAB_TAG_BIN: $CI_REGISTRY_IMAGE:bin
  HUB_TAG: prantlf/alpine-glibc
  HUB_TAG_BIN: prantlf/alpine-glibc:bin

build:
  script:
    - |
      docker run --rm -i \
        -v "${PWD}"/.hadolint.yaml:/.config/hadolint.yaml \
        hadolint/hadolint < Dockerfile
      docker run --rm -i \
        -v "${PWD}"/.hadolint.yaml:/.config/hadolint.yaml \
        hadolint/hadolint < Dockerfile-bin
    - docker build -t $GITLAB_TAG .
    - docker tag $GITLAB_TAG prantlf/alpine-glibc
    - docker build -t $GITLAB_TAG_BIN -f Dockerfile-bin .
    - docker tag $GITLAB_TAG_BIN prantlf/alpine-glibc:bin
    - docker tag $GITLAB_TAG $HUB_TAG
    - docker tag $GITLAB_TAG_BIN $HUB_TAG_BIN
    - echo -n "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $GITLAB_TAG
    - docker push $GITLAB_TAG_BIN
    - echo -n "$DOCKER_TOKEN" | docker login -u prantlf --password-stdin
    - docker push $HUB_TAG
    - docker push $HUB_TAG_BIN
  except:
    - tags
